/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dorm.management;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dell
 */
public class Add_buildng extends javax.swing.JFrame {

   
   Connection con;
    
    public Add_buildng() {
        initComponents();
        connection();
        showTablewomen();
        showTablemen(); 
    }
     public void connection(){
      
         
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormmanage?zeroDateTimeBehavior=convertToNull","root","****");
        } catch (SQLException ex) {
            Logger.getLogger(Login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
               
}
         
     
     
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabfem = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabmale = new javax.swing.JTable();
        jdelfem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jdelmale = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jadd = new javax.swing.JButton();
        jaddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbuild = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jblock = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jfemale = new javax.swing.JRadioButton();
        jmale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(280, 90, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.png"))); // NOI18N
        jLabel2.setText(" building");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 180, 60));

        jtabfem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabfem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 360, 160));

        jtabmale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtabmale);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 360, 160));

        jdelfem.setBackground(new java.awt.Color(255, 102, 102));
        jdelfem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jdelfem.setForeground(new java.awt.Color(255, 255, 255));
        jdelfem.setText("delete");
        jdelfem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdelfemActionPerformed(evt);
            }
        });
        getContentPane().add(jdelfem, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 80, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, -1, 50));

        jdelmale.setBackground(new java.awt.Color(255, 51, 51));
        jdelmale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jdelmale.setForeground(new java.awt.Color(255, 255, 255));
        jdelmale.setText("delete");
        jdelmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdelmaleActionPerformed(evt);
            }
        });
        getContentPane().add(jdelmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, 40));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jadd.setBackground(new java.awt.Color(102, 255, 102));
        jadd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jadd.setText("Add");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });

        jaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddressActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("building adress");

        jbuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuildActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("building name");

        jblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblockActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Block");

        jfemale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jfemale.setText("for women");
        jfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfemaleActionPerformed(evt);
            }
        });

        jmale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmale.setText("for men");
        jmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add building");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(24, 24, 24)))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbuild, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblock, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jadd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfemale)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfemale)
                    .addComponent(jmale)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jadd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 430, 260));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 30, 10));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 670, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close all jframe.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaddressActionPerformed

    private void jbuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuildActionPerformed

    private void jblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblockActionPerformed

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        // TODO add your handling code here:
        
       String insert_sql;
try {
    if (!jmale.isSelected() && !jfemale.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select gender.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
   
    
    if (jmale.isSelected()) {
         String block = jblock.getText();
               if (ismaleBlockAlreadyExists(block)) {
                    JOptionPane.showMessageDialog(this, "Block already exists. Please choose a different block.", "Error", JOptionPane.ERROR_MESSAGE);
                   return;
                   }
              else{
                  insert_sql = "INSERT INTO building_men(block, buildName, buildAddress) VALUES (?, ?, ?)";
                } 
              }
               
    else {
         String block = jblock.getText();
               if (isfemaleBlockAlreadyExists(block)) {
                    JOptionPane.showMessageDialog(this, "Block already exists. Please choose a different block.", "Error", JOptionPane.ERROR_MESSAGE);
                   return;
                   }
              else{
                 insert_sql = "INSERT INTO building_women(block, buildingName, buildingAddress) VALUES (?, ?, ?)";
                } 
    }

    // Validate input fields here if needed

    try (PreparedStatement stmt = con.prepareStatement(insert_sql)) {
        stmt.setInt(1, Integer.parseInt(jblock.getText()));
        stmt.setString(2, jbuild.getText());
        stmt.setString(3, jaddress.getText());
        stmt.executeUpdate();
    }

    JOptionPane.showMessageDialog(this, "Building Added successfully");
     showTablewomen();
     showTablemen(); 
    // Clear input fields
    clearFields();
    // Refresh table and update ID

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error inserting Building: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_jaddActionPerformed

    private void jmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaleActionPerformed
       
         jfemale.setSelected(false);
        
    }//GEN-LAST:event_jmaleActionPerformed

    private void jfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfemaleActionPerformed
        // TODO add your handling code here:
        
         jmale.setSelected(false);
    }//GEN-LAST:event_jfemaleActionPerformed

    private void jdelfemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdelfemActionPerformed

   try {
        int row = jtabfem.getSelectedRow();
        if (row == -1) {
            // No row selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int block = (int) jtabfem.getValueAt(row, 0);

        PreparedStatement stmt = con.prepareStatement("DELETE FROM building_women WHERE block = ?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        stmt.setInt(1, block);

        stmt.executeUpdate();
        

        JOptionPane.showMessageDialog(this, "building deleted successfully");

        stmt.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error deleting building: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       
       showTablemen();   
        
        
    }//GEN-LAST:event_jdelfemActionPerformed

    private void jdelmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdelmaleActionPerformed
        // TODO add your handling code here:
         try {
        int row = jtabmale.getSelectedRow();
        if (row == -1) {
            // No row selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int block = (int) jtabmale.getValueAt(row, 0);

        PreparedStatement stmt = con.prepareStatement("DELETE FROM building_men WHERE block = ?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        stmt.setInt(1, block);

        stmt.executeUpdate();
        

        JOptionPane.showMessageDialog(this, "building deleted successfully");

        stmt.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error deleting building: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       
       showTablemen();   
        
        
        
    }//GEN-LAST:event_jdelmaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

      private void clearFields() {
        jblock.setText("");
        jbuild.setText("");
        jaddress.setText("");
       
    }
      private boolean ismaleBlockAlreadyExists(String block) throws SQLException {
    // Query the database to check if the block already exists
    String query = "SELECT block FROM building_men WHERE block = ? ";
    try (PreparedStatement stmt = con.prepareStatement(query)) {
        stmt.setInt(1, Integer.parseInt(block));
        
        try (ResultSet rs = stmt.executeQuery()) {
            return rs.next();
        }
    }
}
      private boolean isfemaleBlockAlreadyExists(String block) throws SQLException {
    // Query the database to check if the block already exists
    String query = "SELECT block FROM building_women WHERE block = ? ";
    try (PreparedStatement stmt = con.prepareStatement(query)) {
        stmt.setInt(1, Integer.parseInt(block));
        
        try (ResultSet rs = stmt.executeQuery()) {
            return rs.next();
        }
    }
}
      public void showTablemen() 
    {
        DefaultTableModel tablemodel = (DefaultTableModel) jtabmale.getModel();
          JTableHeader header=jtabmale.getTableHeader();
          header.setFont(new Font("Times New Roman",Font.BOLD,18));
        try {
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM building_men");
            ResultSet rs = stmt.executeQuery();

            jtabmale.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            System.out.println("Error showing table...");
        }
    }
           public void showTablewomen() 
    {
        DefaultTableModel tablemodel = (DefaultTableModel) jtabfem.getModel();
          JTableHeader header=jtabfem.getTableHeader();
          header.setFont(new Font("Times New Roman",Font.BOLD,18));
        try {
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM building_women");
            ResultSet rs = stmt.executeQuery();

            jtabfem.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            System.out.println("Error showing table...");
        }
    }
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_buildng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_buildng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_buildng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_buildng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_buildng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jadd;
    private javax.swing.JTextField jaddress;
    private javax.swing.JTextField jblock;
    private javax.swing.JTextField jbuild;
    private javax.swing.JButton jdelfem;
    private javax.swing.JButton jdelmale;
    private javax.swing.JRadioButton jfemale;
    private javax.swing.JRadioButton jmale;
    private javax.swing.JTable jtabfem;
    private javax.swing.JTable jtabmale;
    // End of variables declaration//GEN-END:variables
}
