/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dorm.management;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Dell
 */
public class AssignProctor extends javax.swing.JFrame {

    /**
     * Creates new form AssignProctor
     */
    Connection con;
    public AssignProctor() {
        initComponents();
        connection();
         showTablemen();
         showTablewomen();
        jbuild1.setEnabled(false);
        // Enable the jbuild combo box
        jbuild.setEnabled(false);
            populateBuildComboBox(jbuild, "building_men");
            populateBuildComboBox(jbuild1, "building_women");
    }
    public void connection(){
      
         
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormmanage?zeroDateTimeBehavior=convertToNull","root","****");
        } catch (SQLException ex) {
            Logger.getLogger(Login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
               
}
 private void populateBuildComboBox(JComboBox<String> comboBox, String tableName) {
        comboBox.removeAllItems(); // Clear existing items

        try {
            String query = "SELECT DISTINCT block FROM " + tableName;
            try (PreparedStatement stmt = con.prepareStatement(query);
                 ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    comboBox.addItem(rs.getString("block"));
                }
            }
        } catch (SQLException ex) {
            // Handle the exception
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jmale = new javax.swing.JRadioButton();
        jfem = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jbuild = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbuild1 = new javax.swing.JComboBox<>();
        jAdd = new javax.swing.JButton();
        jphone = new javax.swing.JTextField();
        jname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabfem = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabmen = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdelfem = new javax.swing.JButton();
        jdelmale = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(280, 90, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new student.png"))); // NOI18N
        jLabel1.setText("Assign Proctor ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Assign Proctor");

        jmale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmale.setText("For Male");
        jmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaleActionPerformed(evt);
            }
        });

        jfem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jfem.setText("For Women");
        jfem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Name");

        jbuild.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("block");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("block");

        jbuild1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jAdd.setBackground(new java.awt.Color(0, 51, 255));
        jAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jAdd.setForeground(new java.awt.Color(255, 255, 255));
        jAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jAdd.setText("Assign");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("pro.Id");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("phone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(jmale)
                .addGap(49, 49, 49)
                .addComponent(jfem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbuild, 0, 244, Short.MAX_VALUE)
                            .addComponent(jid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jphone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuild1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jmale)
                    .addComponent(jfem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuild1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 620, 310));

        jtabfem.setBackground(new java.awt.Color(255, 255, 102));
        jtabfem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        jtabfem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabfem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 460, 187));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Male proctor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jtabmen.setBackground(new java.awt.Color(255, 255, 51));
        jtabmen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));
        jtabmen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtabmen);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 450, 187));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Female proctor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 716, -1, -1));

        jdelfem.setBackground(new java.awt.Color(255, 51, 51));
        jdelfem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jdelfem.setForeground(new java.awt.Color(255, 255, 255));
        jdelfem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jdelfem.setText("Delete");
        jdelfem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdelfemActionPerformed(evt);
            }
        });
        getContentPane().add(jdelfem, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, -1, -1));

        jdelmale.setBackground(new java.awt.Color(255, 51, 51));
        jdelmale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jdelmale.setForeground(new java.awt.Color(255, 255, 255));
        jdelmale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jdelmale.setText("Delete");
        jdelmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdelmaleActionPerformed(evt);
            }
        });
        getContentPane().add(jdelmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 120, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close all jframe.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaleActionPerformed
        // TODO add your handling code here:
        
        jfem.setSelected(false);
         jbuild1.setEnabled(false);
        // Enable the jbuild combo box
        jbuild.setEnabled(true);
        
    }//GEN-LAST:event_jmaleActionPerformed

    private void jfemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfemActionPerformed
        // TODO add your handling code here:
           jmale.setSelected(false);
        jbuild1.setEnabled(true);
        jbuild.setEnabled(false);
    }//GEN-LAST:event_jfemActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        
         String insert_sql;

    try {
        if (!jmale.isSelected() && !jfem.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select gender.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        String roomNumber = jroom.getText();
        String buildNo = jmale.isSelected() ? jbuild.getSelectedItem().toString() : jbuild1.getSelectedItem().toString();

        if (jmale.isSelected()) {
            insert_sql = "INSERT INTO menproc(id, name, phone, block) VALUES (?, ?, ?, ?)";
        } else {
            insert_sql = "INSERT INTO femproc(id, name, phone, block) VALUES (?, ?, ?, ?)";
        }

        try (PreparedStatement stmt = con.prepareStatement(insert_sql)) {
            stmt.setInt(1, Integer.parseInt(jid.getText()));
            stmt.setString(2, jname.getText());
             stmt.setString(3, jphone.getText());
            stmt.setString(4, buildNo);
            stmt.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "proctor assigned successfully");
        showTablewomen();
        showTablemen(); 
        clearInputFields();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error assigned room: " + e.getMessage());
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_jAddActionPerformed

    private void jdelmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdelmaleActionPerformed
        // TODO add your handling code here:
         try {
        int row = jtabmen.getSelectedRow();
        if (row == -1) {
            // No row selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id = (int) jtabmen.getValueAt(row, 0);

        PreparedStatement stmt = con.prepareStatement("DELETE FROM menproc WHERE id= ?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        stmt.setInt(1, id);

        stmt.executeUpdate();
        

        JOptionPane.showMessageDialog(this, "proctor deleted successfully");

        stmt.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error deleting proctor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       showTablemen();
        
                    
        
        
    }//GEN-LAST:event_jdelmaleActionPerformed

    private void jdelfemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdelfemActionPerformed
                                          
        // TODO add your handling code here:
         try {
        int row = jtabfem.getSelectedRow();
        if (row == -1) {
            // No row selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id = (int) jtabfem.getValueAt(row, 0);

        PreparedStatement stmt = con.prepareStatement("DELETE FROM femproc WHERE id= ?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        stmt.setInt(1, id);

        stmt.executeUpdate();
        

        JOptionPane.showMessageDialog(this, "proctor deleted successfully");

        stmt.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error deleting proctor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       showTablewomen();
        
        
    }//GEN-LAST:event_jdelfemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void showTablemen() {
   
     DefaultTableModel tablemodel = (DefaultTableModel) jtabmen.getModel();
    JTableHeader header = jtabmen.getTableHeader();
    header.setFont(new Font("Times New Roman", Font.BOLD, 18));

    try {
        PreparedStatement stmt = con.prepareStatement("SELECT id, name, phone,block FROM menproc");
        ResultSet rs = stmt.executeQuery();

        // Clear existing rows and columns in the table model
        tablemodel.setRowCount(0);
        tablemodel.setColumnCount(0);

        // Add column names to the table model
        tablemodel.addColumn("ID");
        tablemodel.addColumn("Name");
        tablemodel.addColumn("Phone");
        tablemodel.addColumn("Block");
     

        // Populate rows in the table model
        while (rs.next()) {
            int id = rs.getInt("id");
            String name = rs.getString("name");
            String phone = rs.getString("phone");
            String block = rs.getString("block");
            

            tablemodel.addRow(new Object[]{id, name, phone, block});
        }

    } catch (SQLException e) {
        System.out.println("Error showing table...");
    }
}
private void clearInputFields() {
    jname.setText("");
    jid.setText("");
    jphone.setText("");
}
public void showTablewomen() {
     DefaultTableModel tablemodel = (DefaultTableModel) jtabfem.getModel();
    JTableHeader header = jtabfem.getTableHeader();
    header.setFont(new Font("Times New Roman", Font.BOLD, 18));

    try {
        PreparedStatement stmt = con.prepareStatement("SELECT id, name, phone,block FROM femproc");
        ResultSet rs = stmt.executeQuery();

        // Clear existing rows and columns in the table model
        tablemodel.setRowCount(0);
        tablemodel.setColumnCount(0);

        // Add column names to the table model
        tablemodel.addColumn("ID");
        tablemodel.addColumn("Name");
        tablemodel.addColumn("Phone");
        tablemodel.addColumn("Block");
     

        // Populate rows in the table model
        while (rs.next()) {
            int id = rs.getInt("id");
            String name = rs.getString("name");
            String phone = rs.getString("phone");
            String block = rs.getString("block");
            

            tablemodel.addRow(new Object[]{id, name, phone, block});
        }

    } catch (SQLException e) {
        System.out.println("Error showing table...");
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignProctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignProctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignProctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignProctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignProctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jbuild;
    private javax.swing.JComboBox<String> jbuild1;
    private javax.swing.JButton jdelfem;
    private javax.swing.JButton jdelmale;
    private javax.swing.JRadioButton jfem;
    private javax.swing.JTextField jid;
    private javax.swing.JRadioButton jmale;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jphone;
    private javax.swing.JTable jtabfem;
    private javax.swing.JTable jtabmen;
    // End of variables declaration//GEN-END:variables
}
