/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dorm.management;

/**
 *
 * @author Dell
 */
public class Main_page extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
    public Main_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jadd = new javax.swing.JButton();
        jroom = new javax.swing.JButton();
        jproct = new javax.swing.JButton();
        jbuild = new javax.swing.JButton();
        jmen = new javax.swing.JButton();
        jwom = new javax.swing.JButton();
        jmaint = new javax.swing.JButton();
        jlogout = new javax.swing.JButton();
        jexit = new javax.swing.JButton();
        jmentmanage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton12.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 960, 650));

        jadd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new student.png"))); // NOI18N
        jadd.setText("Add Student");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });
        jPanel1.add(jadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 190, -1));

        jroom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.png"))); // NOI18N
        jroom.setText("Room");
        jroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jroomActionPerformed(evt);
            }
        });
        jPanel1.add(jroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        jproct.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jproct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jproct.setText("proctor");
        jproct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jproctActionPerformed(evt);
            }
        });
        jPanel1.add(jproct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 190, 40));

        jbuild.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbuild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/List of Paid & Dues Students.png"))); // NOI18N
        jbuild.setText("building");
        jbuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuildActionPerformed(evt);
            }
        });
        jPanel1.add(jbuild, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 190, -1));

        jmen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all student living.png"))); // NOI18N
        jmen.setText("men student");
        jmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenActionPerformed(evt);
            }
        });
        jPanel1.add(jmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 270, 190, 40));

        jwom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jwom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all student living.png"))); // NOI18N
        jwom.setText("women student");
        jwom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwomActionPerformed(evt);
            }
        });
        jPanel1.add(jwom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 360, 190, 40));

        jmaint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update & Delete Student.png"))); // NOI18N
        jmaint.setText("maintenance");
        jmaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaintActionPerformed(evt);
            }
        });
        jPanel1.add(jmaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 450, 190, 40));

        jlogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Leaved students.png"))); // NOI18N
        jlogout.setText("log out");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 150, 48));

        jexit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close all jframe.png"))); // NOI18N
        jexit.setText("exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        jPanel1.add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 140, 48));

        jmentmanage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmentmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jmentmanage.setText("Manage.Ment");
        jmentmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmentmanageActionPerformed(evt);
            }
        });
        jPanel1.add(jmentmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 540, 190, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Dorm Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo 1.jpeg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1460, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        // TODO add your handling code here:
        
        AddStudent addStudent = new AddStudent();

    // Set the visibility of AddStudent to true
    addStudent.setVisible(true);
        
        
        
    }//GEN-LAST:event_jaddActionPerformed

    private void jroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jroomActionPerformed
        // TODO add your handling code here:
          room ob = new room();

    // Set the visibility of AddStudent to true
    ob.setVisible(true);
        
        
    }//GEN-LAST:event_jroomActionPerformed

    private void jproctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jproctActionPerformed
        // TODO add your handling code here:
          AssignProctor ob = new AssignProctor();

    // Set the visibility of AddStudent to true
    ob.setVisible(true);
    }//GEN-LAST:event_jproctActionPerformed

    private void jbuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuildActionPerformed
        // TODO add your handling code here:
         Add_buildng ob = new Add_buildng();

    // Set the visibility of AddStudent to true
   ob.setVisible(true);
        
    }//GEN-LAST:event_jbuildActionPerformed

    private void jmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenActionPerformed
        // TODO add your handling code here:
        ManageMen ob = new ManageMen();

    // Set the visibility of AddStudent to true
   ob.setVisible(true);
        
    }//GEN-LAST:event_jmenActionPerformed

    private void jwomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwomActionPerformed
        // TODO add your handling code here:
         MangeFem ob = new MangeFem();

    // Set the visibility of AddStudent to true
   ob.setVisible(true);
        
    }//GEN-LAST:event_jwomActionPerformed

    private void jmaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaintActionPerformed
        // TODO add your handling code here:
        Maintenance ob = new Maintenance();

    // Set the visibility of AddStudent to true
   ob.setVisible(true);
        
    }//GEN-LAST:event_jmaintActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
        Login_page ob=new Login_page();
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed

this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jexitActionPerformed

    private void jmentmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmentmanageActionPerformed
        // TODO add your handling code here:
        Mentanb ob=new Mentanb();
        ob.setVisible(true);
        
        
    }//GEN-LAST:event_jmentmanageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jadd;
    private javax.swing.JButton jbuild;
    private javax.swing.JButton jexit;
    private javax.swing.JButton jlogout;
    private javax.swing.JButton jmaint;
    private javax.swing.JButton jmen;
    private javax.swing.JButton jmentmanage;
    private javax.swing.JButton jproct;
    private javax.swing.JButton jroom;
    private javax.swing.JButton jwom;
    // End of variables declaration//GEN-END:variables
}
